### ISSUE TITLE
Rename to RED4ext or cpse

### ISSUE THREAD

**Issue by yamashi** [WopsS/RED4ext#1]
RED is a brand not a version, it's like saying Unreal Engine, you need the version ;)

**Comment by WopsS** [comment]
The initial goal was to share this between different versions of REDengine, but seems like it would be too much pain to support so many differences. So I think this would be the best approach, to rename to RED4ext.

**Comment by WopsS** [comment]
I renamed everything in 100e7f2a1dc51dbe63ba29dd92490db43223fb6a.
