### ISSUE TITLE
Update for sneaky game update?

### ISSUE THREAD

**Issue by Ultimation12** [WopsS/RED4ext#15]
**Description**
RED4ext appears to terminate on launch due to file version mismatch. 

**Steps to reproduce**
1. Latest version of game and RED4ext
2. Launch game
3. Either RED4ext terminates or instant crash (depends on installed plugins)
4. Check logs

**Expected behavior**
RED4ext and installed associated plugins function as normal.

**Examples**
Log I got for reference.
> [2022-04-05 11:16:57.718] [RED4ext] [info] RED4ext (v1.5.0) is initializing...
> [2022-04-05 11:16:57.718] [RED4ext] [info] Game version is 1.52
> [2022-04-05 11:16:57.718] [RED4ext] [info] File version 3.0.60.1056
> [2022-04-05 11:16:57.718] [RED4ext] [error] This game version (1.52) is not supported
> [2022-04-05 11:16:57.718] [RED4ext] [error] The current version of RED4ext supports only file version 3.0.59.40169, try updating the mod or downgrading the game
> [2022-04-05 11:17:29.320] [RED4ext] [info] RED4ext is terminating...
> [2022-04-05 11:17:29.320] [RED4ext] [info] RED4ext has been terminated

**Game details (please complete the following information):**
- Platform: Steam
- Version 1.52

**Additional context**
Seems like there was some kind of sneaky ninja update to something overnight. Everything was working fine yesterday. Tried playing today and it crashed. After troubleshooting, the TweakXL plugin caused it to crash, but the author says it's RED4ext that needs an update this time.

**Comment by WopsS** [comment]
Thank you for the report! Unfortunately I could not reproduce it :(

Could you please tell me if you see a message on the screen before this happens and what plugins do you have installed?

**Comment by Ultimation12** [comment]
I don't see a message. The only plugins I have installed are TweakXL and ArchiveXL, and I see the "missing or corrupted scripts" crash error only when the former is installed. Otherwise, the game launches normally, but it seems like without RED4ext. 

Though it has occurred to me to ask, does this output that RED4ext is terminating when the game shuts down or does it only terminate like that when some version is mismatched?

**Comment by WopsS** [comment]
From the error, I assume it is because you also have redscript installed right? TweakXL provides some scripts that are loaded by redscript, if RED4ext fails to load or TweakXL is not loaded, redscript will produce that error.

> Though it has occurred to me to ask, does this output that RED4ext is terminating when the game shuts down or does it only terminate like that when some version is mismatched?
This output is generated when the RED4ext is unloaded from the memory. Might be when the game shutdown, but might also be something else.

I think a better wording for this would be `RED4ext is unloading...` and `RED4ext is unloaded`.

**Comment by Ultimation12** [comment]
I'm pretty sure I have it installed correctly. Like I said, everything was working fine yesterday, and I made no changes to any installed mods between when I stopped last night and when I tried to launch this morning. The only thing I can think of that would've affected this based on that log is that there was some kind of tiny update to whatever file RED4ext checks. But then I'm not a modder myself, thus my report.

**Comment by WopsS** [comment]
The message you showed above, `missing or corrupted scripts` is generated by the game because RED4ext will not load TweakXL / ArchiveXL and another mod is having dependencies on it.

Anyway, this would happen because as you said, there was a sneaky update. I released a new version, [v1.6.0](https://github.com/WopsS/RED4ext/releases/tag/v1.6.0). Could you try with this version and tell me if it works?

**Comment by Ultimation12** [comment]
Looks like that works. Still getting the script crash, but looking at the log, it looks like that's because the plugin authors will have to update their plugins to match. I'll let them know. RED4ext appears to have started fine.

**Comment by WopsS** [comment]
Thanks for testing! I pushed another version, [v1.6.1](https://github.com/WopsS/RED4ext/releases/tag/v1.6.1). This one should load TweakXL and ArchiveXL.

It should be available on GitHub in few minutes.

**Comment by Ultimation12** [comment]
Yup, that's got it. Game boots up, plugins loaded. Awesome!

**Comment by WopsS** [comment]
Nice! Thank you for testing!
