### ISSUE TITLE
Hey there :D great work, the latest version (1.8) keeps crashing, as I have Cyber Engine Tweaks installed too. There is a "Compatible with CET version", however, that one is not compatible with the current Cyberpunk Verision XD. Is there something, I am overlooking, or is a CET-compatible verision for 1.8 in the makings? :) Thank you again so much for the mod!

### ISSUE THREAD

**Issue by CalvinFehl** [WopsS/RED4ext#17]
**Description**

**Steps to reproduce**

**Expected behavior**

**Examples**

**Game details (please complete the following information):**
- Platform: [e.g. GOG]
- Version [e.g. 1.21]

**Additional context**

**Comment by WopsS** [comment]
Hello,

RED4ext is compatible with CET now, so there is no need for a separate ZIP. If you are crashing while using the latest version of RED4ext try to disable GOG Overlay if you are using GOG.
