### ISSUE TITLE
Crash at startup - Incompatible version 

### ISSUE THREAD

**Issue by worxed** [WopsS/RED4ext#18]
**Steps**
After an update of the game, I get a crash at startup.

**Relevant log**

`[2022-11-08 16:42:02.556] [RED4ext] [info] RED4ext (v1.8.0) is initializing...`
`[2022-11-08 16:42:02.556] [RED4ext] [info] Game version is 1.61`
`[2022-11-08 16:42:02.556] [RED4ext] [info] File version is 3.0.66.28510`
`[2022-11-08 16:42:02.556] [RED4ext] [error] This game version (1.61) is not supported`
`[2022-11-08 16:42:02.556] [RED4ext] [error] The current version of RED4ext supports`
`only the following file version(s): 3.0.64.38113`

what I found from the source in src/image.cpp is

`const std::vector<RED4ext::FileVer> Image::GetSupportedVersions() const`
`{`
`    return {RED4EXT_RUNTIME_1_60};`
`}`

Has this been tested with no version requirements? Maybe this is a minor issue if there is support for future versions.

**Game details**
- Platform: GOG/Epic Games
- Version 1.61

**Comment by worxed** [comment]
Posted in NexusMods as well, but github is a better platform for bugs.

**Comment by WopsS** [comment]
The game just updated, since RED4ext is dependent on game's version it will fail to initialize if a different version is detected. I will do a release for patch 1.61 soon.

**Comment by worxed** [comment]
I realize that it's dependent on the game version, I was snooping around the source code myself to maybe help contribute, that's why I was asking :) Thanks for your prompt reply friend. 

Closing bug as it is being handled.

**Comment by WopsS** [comment]
No problem! Thank you for bringing it to my attention too :)

I have released version 1.9.0 to support patch 1.61.

**Comment by worxed** [comment]
I see the updated value is RED4EXT_RUNTIME_LATEST, that should be a little bit more future-proof! :D but so sneaky with those addresses didn't think of that.
