### ISSUE TITLE
Installation on Proton (Linux)

### ISSUE THREAD

**Issue by NXTler** [WopsS/RED4ext#27]
Hey,
I'm having trouble getting RED4ext working on Proton, no log is returned after game start.
I have already installed vcrun2022 via Protontricks for CET and did some more changes, though RED4ext does not seem to work.
Many thanks in advance!

Cyberpunk: 1.63
RED4ext: v1.15.0

**Comment by WopsS** [comment]
Hello,

From what I remember you need to add `winmm.dll` to `WINEDLLOVERRIDES`.

**Comment by NXTler** [comment]
That works for my, thanks!

**Comment by WopsS** [comment]
No problem :)

**Comment by ensignavenger** [comment]
Note for anyone else finding this- Lutris asks for a key,value, where the value is n or b or both.  What worked for me was "n,b"

From what I understand, that means it will load the "native" dll, and then a "builtin" one if that fails.  When I tried "b,n" for the value it did not work.  

Thanks to the folks above, I was able to finally get my mods working on Linux!
