### ISSUE TITLE
RED4ext DLL Error

### ISSUE THREAD

**Issue by DefinitelyNotSai** [WopsS/RED4ext#29]
**Description**
Whenever I launch Cyberpunk, it gives me an DLL error.
![Screenshot 2023-09-28 102433](https://github.com/WopsS/RED4ext/assets/35276105/2fbf2b64-6c39-4b9a-bd0d-ca14c6e121c1)

**Game details**
- Platform: GOG
- Version 2.0

**Comment by DarkPhilosophy** [comment]
I got the same error 
![image](https://github.com/WopsS/RED4ext/assets/19309990/0fa595ea-3520-43e9-99f0-dd8cf66d6b9f)

**Comment by WopsS** [comment]
@DefinitelyNotSai that is not related to RED4ext. I heard that the `version.dll` coming with cybercmd might cause issues. Someone said that they fixed it by reinstalling CET, since it also comes with a `version.dll` file.

@DarkPhilosophy that's a totally different issue. You did not install RED4ext correctly.

**Comment by DefinitelyNotSai** [comment]
> @DefinitelyNotSai that is not related to RED4ext. I heard that the `version.dll` coming with cybercmd might cause issues. Someone said that they fixed it by reinstalling CET, since it also comes with a `version.dll` file.
> 
> @DarkPhilosophy that's a totally different issue. You did not install RED4ext correctly.

I see. I'll try that solution. Thank you for responding.

**Comment by DarkPhilosophy** [comment]
I use the Cyberpunk 2077 Mod Manager, should I install manually?!

**Comment by WopsS** [comment]
@DefinitelyNotSai no problem :) Let me know if it works.

@DarkPhilosophy yes, you should install it manually if you have issues.

**Comment by DefinitelyNotSai** [comment]
Working just fine, thank you again!

**Comment by WopsS** [comment]
No problem! Then I'm going to close this issue :)
