### ISSUE TITLE
Wilson Bug

### ISSUE THREAD

**Issue by Narutomaster700** [WopsS/RED4ext#30]
![screenshot](https://github.com/WopsS/RED4ext/assets/107004598/b747d078-911d-48f4-90ba-48ca589723de)

**Description**
 wilson crash bug

**Steps to reproduce**

**Expected behavior**

**Examples**

**Game details (please complete the following information):**
- Platform: [e.g. Steam]
- Version [e.g. 1.21]

**Additional context**

**Comment by Narutomaster700** [comment]
some reason why I walk up to wilson and try to buy something from him, the game completely crashes

**Comment by WopsS** [comment]
This is not related to RED4ext.
