### ISSUE TITLE
wopss things are missing

### ISSUE THREAD

**Issue by 3xploitch3ats** [WopsS/RED4ext#5]
https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/202
https://prnt.sc/w6zf92
https://github.com/3xploitch3ats/Thunder-Menu/raw/CyberPunk2077/RED4ext-master.zip
....\deps\spdlog\include;%(AdditionalIncludeDirectories)
....\deps\renhook\deps\zydis\dependencies\zycore\include;%(AdditionalIncludeDirectories)

**Comment by WopsS** [comment]
Seems like the build pipeline got fixed by https://github.com/yamashi/CyberEngineTweaks/pull/203.
