### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by esanscoopsers** [WopsS/RED4ext#61]
Linux and game version:
Garuda Linux/Arch, Heroic 2.14.1, Cyberpunk 2077 1.12 (GOG)

Proton version and settings:
proton-ge-custom 2:GE.Proton9.4-1, Esync, Fsync, MangoHud, Feral Gamemode, vkBasalt, d3dcompiler_47, vcrun2022, WINEDLLOVERRIDES="winmm,version=n,b"

Mods:
Lampray 1.3.2 (Linux mod manager), RED4ext 1.24.3, Codeware 1.8.2, Cyber Engine Tweaks 1.32.2, redscript 0.5.19

When combining RED4ext and redscript I get an error message:
![Screenshot_20240421_043022](https://github.com/WopsS/RED4ext/assets/66086944/1e6dc720-ea6f-41c3-bbef-c9c65764a7e4)

Then when I follow the linux modding guide: https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/users-modding-cyberpunk-2077/modding-on-linux

I get this error message as well:
![Screenshot_20240421_045148](https://github.com/WopsS/RED4ext/assets/66086944/51ae297d-302c-4dbf-8879-ed65517305f6)

RED4ext hasn't generated any logs

**Comment by WopsS** [comment]
Hello, the first error message might be because of missing mods.

As for the second one, is `RED4ext.dll` present in `Cyberpunk 2077/red4ext`?

**Comment by xrogaan** [comment]
Can confirm that the mod works on linux. Crash is most likely user error.
