### ISSUE TITLE
Flush logs on crash to desktop

### ISSUE THREAD

**Issue by poirierlouis** [WopsS/RED4ext#66]
**Problem**
When the game crash to desktop, some logs will not be flushed. It can prevents meaningful data to be logged. While a debugger could be used to workaround this behavior, it is not possible / expected when requesting logs from players.

**Solution**
Hook when game's crash handler is triggered, and manually flush current logs.
As proposed by @jac3km4, this [native function](https://github.com/jackhumbert/ctd_helper/blob/f329b3132f9ce7d73f9ba4b9549b7efde74339b5/src/red4ext/Main.cpp#L549) should be a good candidate to hook on.

I'll look at this later and draft a PR.

**Comment by flibdev** [comment]
These are the address patterns from my WIP update for ctd_helper to 2.12a
```cpp
/// @pattern 4C 89 4C 24 20 53 55 56 57 41 54 41 56 48 83 EC 68 80 3D ? ? ? 00 00 49 8B F8 8B F2 48 8B E9
__int64 AssertionFailed(const char *, int, const char *, const char *...);

/// @pattern 48 8B 02 48 83 C0 13 48 89 02 44 0F B6 10 48 FF C0 48 89 02 41 8B C2 4C 8D 15 ? ? ? ? 49 FF
void __fastcall Breakpoint(RED4ext::IScriptable *context, RED4ext::CStackFrame *stackFrame, uintptr_t a3, uintptr_t a4);

/// @pattern 4C 8B DC 49 89 5B 08 49 89 73 10 57 48 83 EC 20 48 8B 05 ? ? ? 01 48 8B FA 40 8A F1 48 83 F8
void __fastcall CrashFunc(uint8_t a1, uintptr_t a2);
```

Addresses for 2.12a are:
```cpp
#define AssertionFailed_Addr 0x29387E8
#define Breakpoint_Addr 0x2026C1C
#define CrashFunc_Addr 0x2939C64
```

I couldn't find any of those addresses in `cyberpunk2077_addresses.json` though

**Comment by poirierlouis** [comment]
Thank you @flibdev :)

**Comment by flibdev** [comment]
Found the address hashes (I had missed the 0x1000 offset):

```cpp
#define AssertionFailed_Hash 4285205681
#define Breakpoint_Hash      2068388886
#define CrashFunc_Hash       2037521395
```

**Comment by poirierlouis** [comment]
Currently I hook `AssertionFailed`, log a crash report and do `App::Get()->Shutdown()` to gracefully shutdown + flush logs, before calling original function. In such case, CrashReporter is not triggered (no popup). Would it be a problem?
@flibdev , crash report is actually what ctd_helper does. Shouldn't it be better to have this right into RED4ext instead of a dependency?
