### ISSUE TITLE
Cannot apply mod

### ISSUE THREAD

**Issue by dpawpxm** [WopsS/RED4ext#72]
The game runs but mods don't apply.
The game hasn't been running since the Windows update. I've tried reinstalling both mods and games, tried Windows rollback, and reinstalled Visual C++, but it doesn't solve it. What should I do?

platform:steam
ver:2.13

**Comment by poirierlouis** [comment]
Can you share latest log file in `/red4ext/logs/` ?

**Comment by dpawpxm** [comment]
It's empty
[red4ext-2024-09-18-18-59-27.log](https://github.com/user-attachments/files/17057638/red4ext-2024-09-18-18-59-27.log)

**Comment by poirierlouis** [comment]
Link doesn't work, but if the file is empty it means RED4ext is not installed correctly I guess.

**Comment by dpawpxm** [comment]
The game was working fine with mods applied, but after a Windows update, the mods no longer apply and errors occur. How can I install them to fix this?

**Comment by WopsS** [comment]
Do you get an error message when you open the game?

**Comment by dpawpxm** [comment]
When you press Run in Red Launcher, an error window appears before the game starts, and when you run it, no window appears and no mods are applied.

**Comment by WopsS** [comment]
Can you copy-paste the error?
