### ISSUE TITLE
RED4ext could not be loaded

### ISSUE THREAD

**Issue by UFOcgj** [WopsS/RED4ext#73]
**Description**

Open the game through Steam and this window pops up.
RED4ext (error 1114)
动态链接库(DLL)初始化例程失败
E:\SteamLibrary\steamapps\common\Cyberpunk 2077\red4ext\RED4ext.dll
RED4ext could not be loaded

**Steps to reproduce**
Everytime trying to open the game

**Examples**
![6a87e53a-ca71-4ddf-a482-075057987871](https://github.com/user-attachments/assets/4743fb5c-22b5-466d-965a-8c56ae205edc)

**Game details (please complete the following information):**
- Platform: Steam
- Version: 2.13

**Additional context**
Try to reinstall it but the problem remains.

**Comment by UFOcgj** [comment]
By the way, my log is completely normal yesterday. But today it only generate a empty file, as you can see below.
[red4ext-2024-09-20-22-27-26.log](https://github.com/user-attachments/files/17083232/red4ext-2024-09-20-22-27-26.log)
[red4ext-2024-09-21-14-55-11.log](https://github.com/user-attachments/files/17083234/red4ext-2024-09-21-14-55-11.log)

**Comment by WopsS** [comment]
Try to install the latest [Visual C++ Redistributable 2022](https://aka.ms/vs/17/release/vc_redist.x64.exe).

**Comment by 0xVirtualProtect** [comment]
I have the same issue and I also reinstalled the Visual C++ Reds and the multiple times the mod itself. Still no luck.

**Comment by WopsS** [comment]
@0xVirtualProtect do you have `cybercmd` installed?

**Comment by 0xVirtualProtect** [comment]
> @0xVirtualProtect do you have `cybercmd` installed?

Yes but I fixed the issue by re-downloading the game and I also bought the DLC so maybe this was also a dependency from other mods? I dont know but I installed every mod as before and even much more than before and it works fine now with no issue. So I cant really tell what it got fixed. But I guess a simple re-download was the key for success. And of course I installed RED4ext and CET first and started the game with these two mods and it worked and I also used Vortex Mod Manager this time.

**Comment by UFOcgj** [comment]
> Try to install the latest [Visual C++ Redistributable 2022](https://aka.ms/vs/17/release/vc_redist.x64.exe).

Thanks, it works for me. I click "repair" and everything is back to normal.

**Comment by WopsS** [comment]
Thank you both for replying. I will close this issue if it got fixed.

**Comment by Aigio1064** [comment]
我也遇到了同样的问题，我推测是Steam或其它游戏平台在安装VC++时省略了一些文件，导致环境损坏，我的情况比较特殊，无法通过MOD信息页面的安装程序修复环境，然后我又尝试使用一个补全VC++环境的第三方软件，但是仍然无法运行，之后使用Hibit Uninstall软件删除了全部的VC++环境并重新安装MOD信息页面的版本，现在完全正常了

I've encountered the same issue. I suspect that Steam or other gaming platforms omitted some files while installing VC++, which corrupted the runtime environment. My case is rather special: I couldn’t repair the environment using the installer on the MOD info page. I then tried a third‑party tool meant to complete the VC++ runtime environment, yet the program still wouldn’t launch. Afterwards, I used HiBit Uninstaller to remove all VC++ runtime packages, reinstalled the versions provided on the MOD info page, and everything works perfectly now.

Windows 10 19045.6466
32GB RAM
RTX 2060 12G
