### ISSUE TITLE
cyberpunk 2077 failed to remove a stale backup file the game will start but no scripts

### ISSUE THREAD

**Issue by gemerok** [WopsS/RED4ext#74]
Hello, I encountered a problem when launching Cyberpunk, this error pops up
![Screenshot_1](https://github.com/user-attachments/assets/326d54f4-92b3-4c36-8719-a5f8445cd1a4)
[Uploading red4ext-2024-10-22-16-59-51.log…]()

**Comment by WopsS** [comment]
Hello,

I don't think this error is caused by RED4ext. Try to delete `<game dir>/r6/cache` and verify your game files in the store launcher.
Sadly, the log file is not completely uploaded :( It is a [blank link]().

**Comment by WopsS** [comment]
@robertfoleyjr can you try to install the latest [Visual C++ Redistributable 2022](https://aka.ms/vs/17/release/vc_redist.x64.exe)?
