### ISSUE TITLE
[FIXED] New 2.12 Game Patch Breaks RED4ext.

### ISSUE THREAD

**Issue by bytorphoto** [WopsS/RED4ext#77]
![Screenshot 2024-12-10 205522](https://github.com/user-attachments/assets/50146187-37cd-432d-aa64-dbfcacbe9446)

Technically not a bug, but definitely an issue. As shown from Screenshot attached. 2.12 game patch breaks RED4ext.

**Comment by WopsS** [comment]
Can you try reinstalling the latest [Visual C++ Redistributable 2022](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

**Comment by bytorphoto** [comment]
That fixed that... now I have other mods to get updated... I keep forgetting that any windows update screws up the VC++ libraries... WHY Microsoft!
