### ISSUE TITLE
Game not starting after 2.2 update

### ISSUE THREAD

**Issue by Sova146** [WopsS/RED4ext#80]
After installing updated RED4ext 2.2 i get this error 
![image](https://github.com/user-attachments/assets/e56df3e6-d7ce-4561-a037-958fb361e920)

**Comment by poirierlouis** [comment]
Did you update all core mods to support v2.2?
You might want to wait a day or two before everything is stable. Otherwise, do share the log from `red4ext/logs/.log`.

**Comment by Sova146** [comment]
The problem was codeware instaled the new one. But now that i fixed that i get this window.  
![image](https://github.com/user-attachments/assets/afc9eb3a-34ba-4621-9510-c4c0c5864572)
