### ISSUE TITLE
HELP! Game not starting after 2.2 update

### ISSUE THREAD

**Issue by PamParam111** [WopsS/RED4ext#85]
![2024-12-11_18-08-07](https://github.com/user-attachments/assets/a4d7881b-1d44-4301-9aba-07cfb650ed11)

**Comment by PamParam111** [comment]
I updated it, but another error appeared
![Uploading 2024-12-11_18-29-27.png…]()

**Comment by Ayaanam11** [comment]
Update ArchiveXL https://www.nexusmods.com/cyberpunk2077/mods/4198
