### ISSUE TITLE
red4ext failed to resolve address for hash 0x28771aba

### ISSUE THREAD

**Issue by BigScrungus** [WopsS/RED4ext#86]
Just updated CET and red4ext and I got an instant crash/failed to start game, with "red4ext failed to resolve address for hash 0x28771aba." 

Tried searching the error code and found no one else with this problem. any suggestions?

**Comment by Sun1ive** [comment]
update codeware/archiveXL
ref: #80

**Comment by BigScrungus** [comment]
preem, thank you! knew I was missing something.
