### ISSUE TITLE
RED4ext not working with patch 2.2

### ISSUE THREAD

**Issue by Pureblend** [WopsS/RED4ext#87]
![RED4exterror](https://github.com/user-attachments/assets/68b846a5-83aa-43fc-bb2c-765b0d444f05)

Been getting this error message whenever I try to start the game. Everything was working fine until update 2.2 dropped.
I've downloaded the latest version of RED4ext and still getting the same error. I've verified the game files and did a clean uninstall and reinstall of RED4ext but am still met with the same error code. 
Gonna try uninstalling the game and reinstalling to see if that works but wondering if anyone knows what the problem could be.

**Comment by WopsS** [comment]
This is not a RED4ext error. It just catches the error from the game and shows it to the user to prevent unknown issues.

You can try removing the `final.redscript` file and verifying the game integrity.
